---
# tasks file for deploy_postgress

- name: Deploy postgresql for RedHat, Fedora, or CenOS
  ansible.builtin.include_tasks: 
    file: postgres_sql_RedHat.yaml
  when: ansible_facts['ansible_distribution'] == "RedHat"

- name: Deploy postgresql for Ubunutu
  ansible.builtin.include_tasks: 
    file: postgres_sql_RedHat.yaml
  when: ansible_facts['ansible_distribution'] == "Ubuntu"